name: karaoke-env
channels:
  - defaults
  - conda-forge # We added a third party channel
dependencies:
  - python=3.8
  - libsndfile
  - ffmpeg
  - pip
  - pip:
      # works for regular pip packages
      - spleeter==2.3.0
      - google-cloud-speech==2.10.0
      - google-cloud-storage==1.42.3
      - fastapi
      - uvicorn
      - starlette
      - pydantic
      - aiofiles
      - python-multipart